In [3]:
!pip install datasets

Collecting datasets
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.11.10)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.27.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.12.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 12.1 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.6 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 13.4 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 11.9 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 15.7 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
Successfully installed datasets-3.2.0 dill-0.3.8 fsspec-2024.9.0 multiprocess-0.70.16 xxhash-3.5.0

In [4]:
from datasets import load_dataset

In [5]:
dataset=load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()

README.md:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

data_jobs.csv:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [6]:
df.head()

        job_title_short  ...                                    job_type_skills
0  Senior Data Engineer  ...                                               None
1          Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2         Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3         Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4         Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...

[5 rows x 17 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [8]:
type(df.job_posted_date[0])

str

In [9]:
import pandas as pd

In [19]:
df['job_posted_date']=pd.to_datetime(df.job_posted_date)

In [20]:
type(df.job_posted_date[0])

pandas._libs.tslibs.timestamps.Timestamp

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(2), int32(1), object(11)
memory usage: 89.2+ MB

In [27]:
df['job_posted_month']=df.job_posted_date.dt.month

In [29]:
df.head(10)

        job_title_short  ... job_posted_month
0  Senior Data Engineer  ...                6
1          Data Analyst  ...                1
2         Data Engineer  ...               10
3         Data Engineer  ...                7
4         Data Engineer  ...                8
5         Data Engineer  ...               11
6  Senior Data Engineer  ...                3
7         Data Engineer  ...               12
8      Business Analyst  ...                6
9        Data Scientist  ...                4

[10 rows x 18 columns]

In [32]:
df.sort_values('job_posted_date',inplace=True)

In [33]:
df

                  job_title_short  ... job_posted_month
108804               Data Analyst  ...                1
96906                Data Analyst  ...                1
98438                Data Analyst  ...                1
110290               Data Analyst  ...                1
72158         Senior Data Analyst  ...                1
...                           ...  ...              ...
351830              Data Engineer  ...               12
362129              Data Engineer  ...               12
327439              Data Engineer  ...               12
112373        Senior Data Analyst  ...               12
90102   Machine Learning Engineer  ...               12

[785741 rows x 18 columns]

In [37]:
df.drop(labels='salary_hour_avg',axis=1,inplace=True)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 108804 to 90102
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785723 non-null  object
 14  job_skills             668704 non-null  object
 15  job_type_skills        668704 non-null  object
 16  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 105.3+ MB

In [39]:
df.dropna(subset=['salary_year_avg'],inplace=True)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22003 entries, 108883 to 327439
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        22003 non-null  object
 1   job_title              22003 non-null  object
 2   job_location           21723 non-null  object
 3   job_via                22003 non-null  object
 4   job_schedule_type      21987 non-null  object
 5   job_work_from_home     22003 non-null  bool
 6   search_location        22003 non-null  object
 7   job_posted_date        22003 non-null  datetime64[ns]
 8   job_no_degree_mention  22003 non-null  bool
 9   job_health_insurance   22003 non-null  bool
 10  job_country            22003 non-null  object
 11  salary_rate            22003 non-null  object
 12  salary_year_avg        22003 non-null  float64
 13  company_name           22003 non-null  object
 14  job_skills             20170 non-null  object
 15  job_type_skills        20170 non-null  object
 16  job_posted_month       22003 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 2.5+ MB

In [41]:
df.dropna(subset=['job_location'],inplace=True)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21723 entries, 108883 to 327439
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        21723 non-null  object
 1   job_title              21723 non-null  object
 2   job_location           21723 non-null  object
 3   job_via                21723 non-null  object
 4   job_schedule_type      21707 non-null  object
 5   job_work_from_home     21723 non-null  bool
 6   search_location        21723 non-null  object
 7   job_posted_date        21723 non-null  datetime64[ns]
 8   job_no_degree_mention  21723 non-null  bool
 9   job_health_insurance   21723 non-null  bool
 10  job_country            21723 non-null  object
 11  salary_rate            21723 non-null  object
 12  salary_year_avg        21723 non-null  float64
 13  company_name           21723 non-null  object
 14  job_skills             19920 non-null  object
 15  job_type_skills        19920 non-null  object
 16  job_posted_month       21723 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 2.5+ MB

In [43]:
df.dropna(subset=["job_schedule_type"],inplace=True)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21707 entries, 108883 to 327439
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        21707 non-null  object
 1   job_title              21707 non-null  object
 2   job_location           21707 non-null  object
 3   job_via                21707 non-null  object
 4   job_schedule_type      21707 non-null  object
 5   job_work_from_home     21707 non-null  bool
 6   search_location        21707 non-null  object
 7   job_posted_date        21707 non-null  datetime64[ns]
 8   job_no_degree_mention  21707 non-null  bool
 9   job_health_insurance   21707 non-null  bool
 10  job_country            21707 non-null  object
 11  salary_rate            21707 non-null  object
 12  salary_year_avg        21707 non-null  float64
 13  company_name           21707 non-null  object
 14  job_skills             19908 non-null  object
 15  job_type_skills        19908 non-null  object
 16  job_posted_month       21707 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 2.5+ MB

In [46]:
df.dropna(subset=["job_skills"],inplace=True)

In [47]:
df.dropna(subset=["job_posted_month"],inplace=True)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19908 entries, 108883 to 327439
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        19908 non-null  object
 1   job_title              19908 non-null  object
 2   job_location           19908 non-null  object
 3   job_via                19908 non-null  object
 4   job_schedule_type      19908 non-null  object
 5   job_work_from_home     19908 non-null  bool
 6   search_location        19908 non-null  object
 7   job_posted_date        19908 non-null  datetime64[ns]
 8   job_no_degree_mention  19908 non-null  bool
 9   job_health_insurance   19908 non-null  bool
 10  job_country            19908 non-null  object
 11  salary_rate            19908 non-null  object
 12  salary_year_avg        19908 non-null  float64
 13  company_name           19908 non-null  object
 14  job_skills             19908 non-null  object
 15  job_type_skills        19908 non-null  object
 16  job_posted_month       19908 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 2.3+ MB

In [50]:
df.count()

job_title_short          19908
job_title                19908
job_location             19908
job_via                  19908
job_schedule_type        19908
job_work_from_home       19908
search_location          19908
job_posted_date          19908
job_no_degree_mention    19908
job_health_insurance     19908
job_country              19908
salary_rate              19908
salary_year_avg          19908
company_name             19908
job_skills               19908
job_type_skills          19908
job_posted_month         19908
dtype: int64

In [51]:
df.describe()

                     job_posted_date  salary_year_avg  job_posted_month
count                          19908     19908.000000      19908.000000
mean   2023-06-11 13:31:10.970263040    123406.688882          5.836749
min              2023-01-01 00:02:56     15000.000000          1.000000
25%    2023-03-16 17:44:41.249999872     90000.000000          3.000000
50%              2023-06-08 23:12:15    116250.000000          6.000000
75%    2023-08-24 07:03:41.249999872    150000.000000          8.000000
max              2023-12-31 23:40:32    960000.000000         12.000000
std                              NaN     46947.204321          3.284071

In [52]:
df.drop_duplicates(inplace=True)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19907 entries, 108883 to 327439
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        19907 non-null  object
 1   job_title              19907 non-null  object
 2   job_location           19907 non-null  object
 3   job_via                19907 non-null  object
 4   job_schedule_type      19907 non-null  object
 5   job_work_from_home     19907 non-null  bool
 6   search_location        19907 non-null  object
 7   job_posted_date        19907 non-null  datetime64[ns]
 8   job_no_degree_mention  19907 non-null  bool
 9   job_health_insurance   19907 non-null  bool
 10  job_country            19907 non-null  object
 11  salary_rate            19907 non-null  object
 12  salary_year_avg        19907 non-null  float64
 13  company_name           19907 non-null  object
 14  job_skills             19907 non-null  object
 15  job_type_skills        19907 non-null  object
 16  job_posted_month       19907 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 2.3+ MB

In [55]:
df['job_country'].head(20)

108883    United States
334082        Argentina
365786    United States
366073    United States
108099    United States
78139     United States
705374    United States
47131     United States
69156     United States
60095     United States
41270     United States
776813            Sudan
777985            Sudan
153859    United States
2862      United States
449502    United States
291092    United States
728461    United States
81058     United States
83329     United States
Name: job_country, dtype: object

In [56]:
us_jobs=df[df['job_country']=='United States']
us_jobs

              job_title_short  ... job_posted_month
108883         Data Scientist  ...                1
365786       Business Analyst  ...                1
366073           Data Analyst  ...                1
108099         Data Scientist  ...                1
78139           Data Engineer  ...                1
...                       ...  ...              ...
679         Software Engineer  ...               12
3448     Senior Data Engineer  ...               12
186163  Senior Data Scientist  ...               12
421728           Data Analyst  ...               12
313161         Data Scientist  ...               12

[14153 rows x 17 columns]

In [67]:
us_jobs.groupby('salary_year_avg').min()

                       job_title_short  ... job_posted_month
salary_year_avg                         ...
23496.0                  Data Engineer  ...                2
25000.0                  Data Engineer  ...                7
30000.0                   Data Analyst  ...                8
30594.0                 Data Scientist  ...                2
30750.0                 Data Scientist  ...                3
...                                ...  ...              ...
450000.0                Data Scientist  ...                8
463500.0         Senior Data Scientist  ...               11
525000.0                 Data Engineer  ...                4
585000.0                Data Scientist  ...               12
960000.0                Data Scientist  ...                5

[2188 rows x 16 columns]

In [70]:
us_jobs.groupby('job_title_short')[['salary_year_avg']]